/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package telecmi_example_java;

import static spark.Spark.*;

import com.cedarsoftware.util.io.JsonWriter;

public class App {

	public static void main(String[] args) {

		post("/webhook/cdr", (req, res) -> {

			System.out.println("You got CDR from TeleCMI Platform");
			String cmiJSON = JsonWriter.formatJson(req.body());
			System.out.println(cmiJSON);
			res.status(204);
			return "";
		});

		port(5000);

	}
}
